# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

#format = '$all'
# Add the module to your prompt format (e.g., at the beginning)
#format = "${custom.reboot}$all"
#format = '$all'

# Which is equivalent to
format = """
$username\
$hostname\
${custom.hostname_local}\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$direnv\
$env_var\
$custom\
$sudo\
$line_break\
$character"""

#[custom.reboot]
#command = 'echo "⚠️ Reboot"'
#shell = ["bash", "-c"]
#format = '[$output]($style)'
#style = "bold yellow"
#when = 'test -f /var/run/reboot-required'

[username]
show_always = true
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = true
ssh_symbol = ' '
format = '[$ssh_symbol](bold yellow)[$hostname](bold blue)'
disabled = false

[custom.hostname_local]
command = 'hostname'
when = 'test -z "$SSH_CONNECTION"'
format = '@[$output]($style)'
style = 'bold blue'
disabled = false

[directory]
truncation_symbol = '…/'
truncation_length = 3
truncate_to_repo = false
# fish_style_pwd_dir_length = 4
format = ':[$path]($style)[$read_only]($read_only_style) '

#[git_branch]
#format = '[$symbol$branch(:$remote_branch)]($style) '
#symbol = ''
