# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

#format = '$all'
# Add the module to your prompt format (e.g., at the beginning)
#format = "${custom.reboot}$all"
#format = '$all'

# Which is equivalent to
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$direnv\
$env_var\
$custom\
$sudo\
$line_break\
$character"""

#[custom.reboot]
#command = 'echo "⚠️ Reboot"'
#shell = ["bash", "-c"]
#format = '[$output]($style)'
#style = "bold yellow"
#when = 'test -f /var/run/reboot-required'

[username]
show_always = true
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = false
ssh_symbol = ''
format = '@[$ssh_symbol](bold blue)[$hostname](bold blue)'
disabled = false

[directory]
truncation_symbol = '…/'
fish_style_pwd_dir_length = 2
format = ':[$path]($style)[$read_only]($read_only_style) '

#[git_branch]
#format = '[$symbol$branch(:$remote_branch)]($style) '
#symbol = ''
